image: registry.gitlab.com/fdroid/ci-images-repomaker:latest

stages:
  - test
  - deploy

pep8:
  stage: test
  script:
    - ./tests/test-pep8.sh

pylint:
  stage: test
  before_script:
    - pip3 install -r requirements.txt
    - pip3 install -r requirements-dev.txt

  script:
    - ./tests/test-pylint.sh

units:
  stage: test
  cache:
    paths:
      - /usr/local/lib/python3.5/dist-packages
      - node_modules

  before_script:
    - ./setup.sh
    - pip3 install -r requirements-dev.txt
    - npm install --user

  script:
    - ./tests/test-units.sh

docker:
  stage: deploy
  image: docker:git
  services:
    - docker:dind

  before_script:
    # avoid invalid reference format: repository name must be lowercase
    - export NAMESPACE="$(echo "${CI_PROJECT_NAMESPACE}" | tr A-Z a-z)"
    - export NAME="$(echo "${CI_PROJECT_NAME}" | tr A-Z a-z)"
    - export IMAGE="registry.gitlab.com/${NAMESPACE}/${NAME}/latest"
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} registry.gitlab.com
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE

  when: on_success
  only:
    - master
  environment:
      name: docker
