version: '2'

services:
  db:
    image: postgres
    volumes:
      - ${REPOMAKER_PATH}/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  dbadmin:
    image: fenglc/pgadmin4:alpine
    ports:
      - "${DB_ADMIN_PORT}:5050"
    links:
      - db:postgres
    depends_on:
      - db

  web:
    build: .
    container_name: repomaker-web
    hostname: ${REPOMAKER_HOSTNAME}
    domainname: ${REPOMAKER_HOSTNAME}
    env_file:
      - .env
    command: sleep infinity
    volumes:
      - .:/repomaker
      - ${REPOMAKER_PATH}/data:/repomaker/data
      - ./docker/settings_docker.py:/repomaker/repomaker/settings_docker.py
      - ./docker/apache.conf:/etc/apache2/sites-available/repomaker.conf
      - ./docker/wait-for:/repomaker/wait-for
      - ./docker/httpd-foreground:/repomaker/httpd-foreground
      - ./docker/ssh_config:/etc/ssh/ssh_config
    working_dir: /repomaker
    ports:
      - "${REPOMAKER_PORT}:80"
    depends_on:
      - db
    restart: unless-stopped

  tasks:
    build: .
    container_name: repomaker-tasks
    env_file:
      - .env
    command: sleep infinity
    volumes:
      - .:/repomaker
      - ${REPOMAKER_PATH}/data:/repomaker/data
      - ./docker/settings_docker.py:/repomaker/repomaker/settings_docker.py
      - ./docker/apache.conf:/etc/apache2/sites-available/repomaker.conf
      - ./docker/wait-for:/repomaker/wait-for
      - ./docker/httpd-foreground:/repomaker/httpd-foreground
      - ./docker/ssh_config:/etc/ssh/ssh_config
    working_dir: /repomaker
    depends_on:
      - db
      - web
    restart: unless-stopped

  bash:
    build: .
    container_name: repomaker-bash
    env_file:
      - .env
    command: sleep infinity
    volumes:
      - .:/repomaker
      - ${REPOMAKER_PATH}/data:/repomaker/data
      - ./docker/settings_docker.py:/repomaker/repomaker/settings_docker.py
      - ./docker/apache.conf:/etc/apache2/sites-available/repomaker.conf
      - ./docker/wait-for:/repomaker/wait-for
      - ./docker/httpd-foreground:/repomaker/httpd-foreground
      - ./docker/ssh_config:/etc/ssh/ssh_config
    working_dir: /repomaker

# vim: set tabstop=2:softtabstop=2:shiftwidth=2
