# Generated by Django 2.2.28 on 2024-12-09 13:38

from django.db import migrations, models
import django.db.models.deletion
import repomaker.storage


class Migration(migrations.Migration):

    dependencies = [
        ('repomaker', 'default_remote_repositories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RcloneStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled', models.BooleanField(default=False)),
                ('bucket', models.CharField(max_length=128)),
                ('rclone_config', models.CharField(max_length=32)),
                ('endpoint', models.CharField(max_length=100)),
                ('rclone_config_text_field', models.TextField()),
                ('config_file', models.FileField(blank=True, storage=repomaker.storage.PrivateStorage(), upload_to=repomaker.storage.get_identity_file_path)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repomaker.Repository')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilebaseStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled', models.BooleanField(default=False)),
                ('type', models.CharField(default='s3', editable=False, max_length=32)),
                ('provider', models.CharField(default='Other', editable=False, max_length=32)),
                ('access_key_id', models.CharField(max_length=255)),
                ('secret_access_key', models.CharField(max_length=255)),
                ('region', models.CharField(default='us-east-1', editable=False, max_length=32)),
                ('endpoint', models.CharField(default='https://s3.filebase.com', editable=False, max_length=32)),
                ('bucket', models.CharField(max_length=128)),
                ('config_file', models.FileField(blank=True, storage=repomaker.storage.PrivateStorage(), upload_to=repomaker.storage.get_identity_file_path)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repomaker.Repository')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='B2Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled', models.BooleanField(default=False)),
                ('type', models.CharField(default='b2', editable=False, max_length=32)),
                ('account', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=128)),
                ('config_file', models.FileField(blank=True, storage=repomaker.storage.PrivateStorage(), upload_to=repomaker.storage.get_identity_file_path)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repomaker.Repository')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
