# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-03 11:48
from __future__ import unicode_literals

from django.db import migrations, models
from repomaker.migrations.default_categories import DEFAULT_CATEGORIES


def forwards_func(apps, schema_editor):
    # noinspection PyPep8Naming
    Category = apps.get_model("repomaker", "Category")
    db_alias = schema_editor.connection.alias

    for category in DEFAULT_CATEGORIES:
        dbCategory = Category.objects.using(db_alias).get(user=None, name=category[0])
        dbCategory.color = category[1]
        dbCategory.save()


def reverse_func(apps, schema_editor):
    # noinspection PyPep8Naming
    pass
    # noop, let colors being deleted when column will be removed.


class Migration(migrations.Migration):

    dependencies = [
        ('repomaker', 'default_categories'),
        ('repomaker', 'default_remote_repositories'),
        ('repomaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=8, blank=True, default=''),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
